package com.person124.elrh;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Arrays;
import java.util.Random;

import com.person124.elrh.events.EntityDeathEvent;
import com.person124.elrh.events.PlayerDisconnectEvent;
import com.person124.elrh.events.PlayerSyncingEvent;
import com.person124.elrh.events.WorldInitEvent;
import com.person124.elrh.handler.EldritchGUIHandler;
import com.person124.elrh.network.PacketHandler;
import com.person124.elrh.network.packet.EldritchPacketGetRitual;
import com.person124.elrh.network.sync.EldritchPacketBooleanSync;
import com.person124.elrh.network.sync.EldritchPacketPlayerSync;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.RenderItem;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@Mod(modid = Eldritch.MODID, version = Eldritch.VERSION)
public class Eldritch {

	@Instance
	public static Eldritch instance = new Eldritch();

	public static final String MODID = "eldritch";
	public static final String VERSION = "0.71.0";
	public static final Random RAND = new Random();

	@SideOnly(Side.CLIENT)
	public static RenderItem renderItem;
	public static boolean isClient;

	public static PacketHandler packetHandler;
	public static EldritchWorldSaveData worldData;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		if (event.getSide() == Side.CLIENT) {
			try {
				File f = new File("version.txt");
				BufferedReader reader = new BufferedReader(new FileReader(f));

				int i = Integer.valueOf(reader.readLine());
				i++;
				reader.close();

				f.delete();
				f.createNewFile();

				FileWriter writer = new FileWriter(f);
				writer.write(String.valueOf(i));
				writer.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}

		event.getModMetadata().autogenerated = false;
		event.getModMetadata().name = "Eldritch";
		event.getModMetadata().authorList = Arrays.asList("person124");
		event.getModMetadata().version = VERSION;
		event.getModMetadata().modId = MODID;

		MinecraftForge.EVENT_BUS.register(new WorldInitEvent());
		MinecraftForge.EVENT_BUS.register(new PlayerSyncingEvent());
		MinecraftForge.EVENT_BUS.register(new EntityDeathEvent());
		MinecraftForge.EVENT_BUS.register(new PlayerDisconnectEvent());

		FMLCommonHandler.instance().bus().register(new PlayerDisconnectEvent());

		NetworkRegistry.INSTANCE.registerGuiHandler(Eldritch.instance, new EldritchGUIHandler());
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		if (event.getSide() == Side.CLIENT) renderItem = Minecraft.getMinecraft().getRenderItem();
		isClient = event.getSide() == Side.CLIENT;

		packetHandler = new PacketHandler(MODID);
		packetHandler.registerPacket(EldritchPacketBooleanSync.class, new EldritchPacketBooleanSync.Handler(), Side.SERVER);
		packetHandler.registerBothPacket(EldritchPacketGetRitual.class, new EldritchPacketGetRitual.Handler());
		packetHandler.registerBothPacket(EldritchPacketPlayerSync.class, new EldritchPacketPlayerSync.Handler());

		ElrhBlocks.init();
		ElrhItems.init();
	}

}
